### ISSUE TITLE
cannot import name "api2msl_pb2"

### ISSUE THREAD

**Issue by whrenstone** [cap-ntu/Video-to-Online-Platform#13]
Thanks for your sharing. When i run " python manage.py makemigrations rest api ", an error showed with the notice "cannot import nam api2msl_pb2", i have searched on stackoverflow, but i get no idea.I also searched in the file of api2msl.proto without any finding..
Any suggestion will be appreciated! Thanks!   @QimingAi @pupboss @Lukeeeeee

**Comment by YuanmingLeee** [comment]
Hi can you try this at the `server` dir before run `python manage.py makemigrations restapi`:
```
python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. protos/api2msl.proto
```

**Comment by whrenstone** [comment]
@YuanmingLeee  Thanks for your advice. No problem from now :)
