### ISSUE TITLE
visual_model_server.py 50051 not load

### ISSUE THREAD

**Issue by chen849157649** [cap-ntu/Video-to-Online-Platform#16]
There has been no reaction, no error occurred at the same time, can you help me? thank you

**Comment by YuanmingLeee** [comment]
Hi, can you provide the whole log printed out, since the description is quite confusing?

**Comment by chen849157649** [comment]
@YuanmingLeee ,
i only deploy audio_runner,  feature_extract_runner and visual_runner,

print log as bellow:
2019-11-19 18:04:26,982 - audio_model_server - INFO - Logger audio_model_server created
WARNING: Logging before flag parsing goes to stderr.
I1119 18:04:26.982776 140234722244352 logger.py:47] Logger audio_model_server created
2019-11-19 18:04:27,601 - feature_extract_model_server - INFO - Logger feature_extract_model_server created
I1119 18:04:27.601432 140234722244352 logger.py:47] Logger feature_extract_model_server created
2019-11-19 18:04:27,695 - visual_model_server - INFO - Logger visual_model_server created
I1119 18:04:27.695462 140234722244352 logger.py:47] Logger visual_model_server created
2019-11-19 18:04:27,695 - model_server - INFO - Logger model_server created
I1119 18:04:27.695734 140234722244352 logger.py:47] Logger model_server created
2019-11-19 18:04:27,695 - model_server - INFO - Starting model servers
I1119 18:04:27.695811 140234722244352 logger.py:50] Starting model servers
2019-11-19 18:04:27,728 - feature_extract_model_server - INFO - Using GPU:1
I1119 18:04:27.728969 140234722244352 logger.py:50] Using GPU:1
W1119 18:04:27.730422 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/../hysia/models/nlp/sentence.py:22: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-11-19 18:04:27,730 - visual_model_server - INFO - Using GPU:1
2019-11-19 18:04:27,730 - audio_model_server - INFO - Using GPU:0
I1119 18:04:27.730248 140234722244352 logger.py:50] Using GPU:1
I1119 18:04:27.730294 140234722244352 logger.py:50] Using GPU:0
W1119 18:04:27.756479 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/model_server/audio_model_server.py:36: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

W1119 18:04:27.756540 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/model_server/visual_model_server.py:92: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

W1119 18:04:27.756973 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/model_server/audio_model_server.py:37: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W1119 18:04:27.757036 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/model_server/visual_model_server.py:93: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W1119 18:04:27.872826 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/../hysia/models/scene/soundnet_classifier.py:16: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W1119 18:04:27.873150 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/../hysia/models/scene/soundnet_classifier.py:18: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W1119 18:04:28.095454 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/../hysia/models/text/tf_detector.py:26: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W1119 18:04:28.095776 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/../hysia/models/text/tf_detector.py:28: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W1119 18:04:29.202230 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/../hysia/models/nlp/sentence.py:27: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-11-19 18:04:29,794 - audio_model_server - INFO - Soundnet loaded
I1119 18:04:29.794316 140234722244352 logger.py:50] Soundnet loaded
2019-11-19 18:04:29,799 - audio_model_server - INFO - Listening on port 50052
I1119 18:04:29.799284 140234722244352 logger.py:50] Listening on port 50052
2019-11-19 18:04:29,800 - visual_model_server - INFO - Finished loading text detector
I1119 18:04:29.800249 140234722244352 logger.py:50] Finished loading text detector
W1119 18:04:30.138922 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/../hysia/models/nlp/sentence.py:30: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W1119 18:04:30.277762 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/../hysia/models/nlp/sentence.py:31: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

2019-11-19 18:04:30,822 - visual_model_server - INFO - Finished loading face models
I1119 18:04:30.822431 140234722244352 logger.py:50] Finished loading face models
W1119 18:04:31.028132 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/../hysia/models/nlp/sentence.py:32: The name tf.tables_initializer is deprecated. Please use tf.compat.v1.tables_initializer instead.

W1119 18:04:32.529452 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/model_server/feature_extract_model_server.py:53: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

2019-11-19 18:04:35,712 - visual_model_server - INFO - Finished loading scene classifier
I1119 18:04:35.712158 140234722244352 logger.py:50] Finished loading scene classifier
W1119 18:04:37.157152 140234722244352 deprecation_wrapper.py:119] From /data/chengt1/project/Video-to-Online-Platform/server/../hysia/models/object/tf_detector.py:35: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

==============Finish loading resnet50===============
2019-11-19 18:04:38,524 - feature_extract_model_server - INFO - Listening on port 50055
I1119 18:04:38.524710 140234722244352 logger.py:50] Listening on port 50055



 i select the fours engine:
       self.ctpn_engine = load_ctpn_engine()
        self.face_engine = load_face_engine()
        self.places365_engine = load_places365_engine()
        self.detector_engine = load_detector_engine()
When the four models are not loaded at the same time, only  three of them are selected. The 50051 port can be started successfully , is GPU memory not enough ???, but this 11G
![微信截图_20191119181238](https://user-images.githubusercontent.com/32058220/69137684-36749a80-0af8-11ea-948f-3d3bd1448fc1.png)
